language: c

os:
  - linux
#  - osx

addons:
  apt:
    packages:
    # packages list: https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
    - oss-compat

# container-based builds
sudo: false

compiler:
  - gcc
  - clang

script:
  - make

